/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tatianagarcia_lab5p2;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author tatig
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        jt_personaje.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_agregarpersonajes = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_universo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tf_poder = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_debilidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_fuerza = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_agfisica = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_agmental = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_vida = new javax.swing.JTextField();
        jb_add = new javax.swing.JButton();
        jl_regresar = new javax.swing.JLabel();
        jf_listarpersonajes = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_personajes = new javax.swing.JTree();
        jl_regresar1 = new javax.swing.JLabel();
        jp_listpersonaje = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_infopersonaje = new javax.swing.JList<>();
        jt_personaje = new javax.swing.JTextField();
        jp_listpersonajes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_personajes = new javax.swing.JTable();
        jp_modpersonaje = new javax.swing.JPanel();
        jp_delpersonaje = new javax.swing.JPanel();
        pm_crud = new javax.swing.JPopupMenu();
        mi_listar = new javax.swing.JMenuItem();
        mi_modificar = new javax.swing.JMenuItem();
        mi_eliminar = new javax.swing.JMenuItem();
        jf_seleccion = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cb_personaje = new javax.swing.JComboBox<>();
        cb_personaje2 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jb_game = new javax.swing.JButton();
        jl_regresar2 = new javax.swing.JLabel();
        jf_game = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_juego = new javax.swing.JTextArea();
        jb_resistencia = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jb_mental = new javax.swing.JToggleButton();
        jb_fisico = new javax.swing.JToggleButton();
        jl_personaje = new javax.swing.JLabel();
        jl_regresar3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jb_agregarp = new javax.swing.JButton();
        jb_listarp = new javax.swing.JButton();
        jb_batalla = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar Personaje");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Universo:");

        cb_universo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DC", "Marvel", "Capcom", "Midway Games" }));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Poder:");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Debilidad:");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fuerza:");

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Agilidad Fisica:");

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Agilidad mental:");

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Puntos de vida:");

        jb_add.setBackground(new java.awt.Color(204, 0, 0));
        jb_add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_add.setForeground(new java.awt.Color(204, 204, 204));
        jb_add.setText("Agregar");
        jb_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_addActionPerformed(evt);
            }
        });

        jl_regresar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jl_regresar.setForeground(new java.awt.Color(255, 255, 255));
        jl_regresar.setText("<< Regresar");
        jl_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_regresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_regresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_regresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_poder, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_fuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(cb_universo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_agfisica, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_agmental, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_add)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_universo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_agfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_agmental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_fuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(120, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_add)
                            .addComponent(jl_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jf_agregarpersonajesLayout = new javax.swing.GroupLayout(jf_agregarpersonajes.getContentPane());
        jf_agregarpersonajes.getContentPane().setLayout(jf_agregarpersonajesLayout);
        jf_agregarpersonajesLayout.setHorizontalGroup(
            jf_agregarpersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jf_agregarpersonajesLayout.setVerticalGroup(
            jf_agregarpersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jf_listarpersonajes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Listar Personaje");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 0, 800, 52);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        jt_personajes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_personajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_personajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_personajes);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(12, 70, 134, 382);

        jl_regresar1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jl_regresar1.setForeground(new java.awt.Color(255, 255, 255));
        jl_regresar1.setText("<< Regresar");
        jl_regresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_regresar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_regresar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_regresar1MouseExited(evt);
            }
        });
        jPanel5.add(jl_regresar1);
        jl_regresar1.setBounds(12, 458, 80, 30);

        jp_listpersonaje.setBackground(new java.awt.Color(153, 153, 153));

        jScrollPane3.setViewportView(jl_infopersonaje);

        jt_personaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jp_listpersonajeLayout = new javax.swing.GroupLayout(jp_listpersonaje);
        jp_listpersonaje.setLayout(jp_listpersonajeLayout);
        jp_listpersonajeLayout.setHorizontalGroup(
            jp_listpersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_listpersonajeLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(jp_listpersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jt_personaje, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        jp_listpersonajeLayout.setVerticalGroup(
            jp_listpersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_listpersonajeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jt_personaje, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel5.add(jp_listpersonaje);
        jp_listpersonaje.setBounds(164, 70, 624, 409);

        jp_listpersonajes.setBackground(new java.awt.Color(153, 153, 153));
        jp_listpersonajes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_personajes.setBackground(new java.awt.Color(0, 51, 153));
        tb_personajes.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tb_personajes.setForeground(new java.awt.Color(255, 255, 255));
        tb_personajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Poder", "Debilidad", "Universo", "Fuerza", "Ag. Fisica", "Ag. Mental", "Vida"
            }
        ));
        tb_personajes.setGridColor(new java.awt.Color(204, 0, 51));
        tb_personajes.setSelectionBackground(new java.awt.Color(153, 255, 255));
        tb_personajes.setSelectionForeground(new java.awt.Color(204, 0, 51));
        jScrollPane2.setViewportView(tb_personajes);

        jp_listpersonajes.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 410));

        jPanel5.add(jp_listpersonajes);
        jp_listpersonajes.setBounds(164, 70, 624, 409);

        jp_modpersonaje.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jp_modpersonajeLayout = new javax.swing.GroupLayout(jp_modpersonaje);
        jp_modpersonaje.setLayout(jp_modpersonajeLayout);
        jp_modpersonajeLayout.setHorizontalGroup(
            jp_modpersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        jp_modpersonajeLayout.setVerticalGroup(
            jp_modpersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jPanel5.add(jp_modpersonaje);
        jp_modpersonaje.setBounds(164, 70, 624, 409);

        jp_delpersonaje.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jp_delpersonajeLayout = new javax.swing.GroupLayout(jp_delpersonaje);
        jp_delpersonaje.setLayout(jp_delpersonajeLayout);
        jp_delpersonajeLayout.setHorizontalGroup(
            jp_delpersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        jp_delpersonajeLayout.setVerticalGroup(
            jp_delpersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jPanel5.add(jp_delpersonaje);
        jp_delpersonaje.setBounds(164, 70, 624, 409);

        jf_listarpersonajes.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 506));

        mi_listar.setText("Listar");
        mi_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_listarActionPerformed(evt);
            }
        });
        pm_crud.add(mi_listar);

        mi_modificar.setText("Modificar");
        pm_crud.add(mi_modificar);

        mi_eliminar.setText("Eliminar");
        mi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_eliminarActionPerformed(evt);
            }
        });
        pm_crud.add(mi_eliminar);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Simulación de Batalla");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cb_personaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Midway Games" }));
        cb_personaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_personajeItemStateChanged(evt);
            }
        });

        cb_personaje2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Midway Games" }));
        cb_personaje2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_personaje2ItemStateChanged(evt);
            }
        });

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jList1);

        jList2.setModel(new DefaultListModel());
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jList2);

        jb_game.setBackground(new java.awt.Color(255, 0, 51));
        jb_game.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jb_game.setForeground(new java.awt.Color(255, 255, 255));
        jb_game.setText("Game");
        jb_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gameActionPerformed(evt);
            }
        });

        jl_regresar2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jl_regresar2.setForeground(new java.awt.Color(255, 255, 255));
        jl_regresar2.setText("<< Regresar");
        jl_regresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_regresar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_regresar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_regresar2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_personaje, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_personaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jl_regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_game)
                .addGap(22, 22, 22))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_personaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_personaje2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 46, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_game)
                    .addComponent(jl_regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jf_seleccionLayout = new javax.swing.GroupLayout(jf_seleccion.getContentPane());
        jf_seleccion.getContentPane().setLayout(jf_seleccionLayout);
        jf_seleccionLayout.setHorizontalGroup(
            jf_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jf_seleccionLayout.setVerticalGroup(
            jf_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        ta_juego.setColumns(20);
        ta_juego.setRows(5);
        jScrollPane4.setViewportView(ta_juego);

        jb_resistencia.setBackground(new java.awt.Color(51, 51, 255));
        jb_resistencia.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jb_resistencia.setForeground(new java.awt.Color(255, 255, 255));
        jb_resistencia.setText("Resistencia");
        jb_resistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_resistenciaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel13.setText("Ataque:");

        jb_mental.setBackground(new java.awt.Color(51, 51, 255));
        jb_mental.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jb_mental.setForeground(new java.awt.Color(255, 255, 255));
        jb_mental.setText("Mental");
        jb_mental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mentalActionPerformed(evt);
            }
        });

        jb_fisico.setBackground(new java.awt.Color(51, 51, 255));
        jb_fisico.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jb_fisico.setForeground(new java.awt.Color(255, 255, 255));
        jb_fisico.setText("Fisico");
        jb_fisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_fisicoActionPerformed(evt);
            }
        });

        jl_personaje.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jl_personaje.setForeground(new java.awt.Color(0, 255, 0));
        jl_personaje.setText("Personaje 1");

        jl_regresar3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jl_regresar3.setForeground(new java.awt.Color(255, 255, 255));
        jl_regresar3.setText("<< Regresar");
        jl_regresar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_regresar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_regresar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_regresar3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jb_resistencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(jb_mental, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                .addComponent(jb_fisico, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_regresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl_personaje)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl_personaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl_regresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_resistencia)
                    .addComponent(jb_mental)
                    .addComponent(jb_fisico))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jf_gameLayout = new javax.swing.GroupLayout(jf_game.getContentPane());
        jf_game.getContentPane().setLayout(jf_gameLayout);
        jf_gameLayout.setHorizontalGroup(
            jf_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jf_gameLayout.setVerticalGroup(
            jf_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jb_agregarp.setBackground(new java.awt.Color(0, 0, 204));
        jb_agregarp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_agregarp.setForeground(new java.awt.Color(204, 204, 204));
        jb_agregarp.setText("Agregar Personaje");
        jb_agregarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarpActionPerformed(evt);
            }
        });

        jb_listarp.setBackground(new java.awt.Color(0, 0, 204));
        jb_listarp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_listarp.setForeground(new java.awt.Color(204, 204, 204));
        jb_listarp.setText("Listar Personajes");
        jb_listarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_listarpActionPerformed(evt);
            }
        });

        jb_batalla.setBackground(new java.awt.Color(0, 0, 204));
        jb_batalla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_batalla.setForeground(new java.awt.Color(204, 204, 204));
        jb_batalla.setText("Simulación de Batalla");
        jb_batalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_batallaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jb_batalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_agregarp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_listarp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jb_agregarp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jb_listarp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jb_batalla, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_agregarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarpActionPerformed
        agregarpersonaje();
    }//GEN-LAST:event_jb_agregarpActionPerformed

    private void jb_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_addActionPerformed
                if (!"".equals(tf_nombre.getText())
                    &&!"".equals(tf_poder.getText())
                    &&!"".equals(tf_debilidad.getText())
                    &&!"".equals(tf_agmental.getText())
                    &&!"".equals(tf_agfisica.getText())
                    &&!"".equals(tf_fuerza.getText())
                    &&!"".equals(tf_vida.getText())   
                    &&!"".equals(cb_universo.getSelectedItem())  ) {
            
                personaje.add(new Personajes(tf_nombre.getText(), tf_poder.getText(),
                        tf_debilidad.getText(), cb_universo.getSelectedItem().toString(),
                        Double.parseDouble(tf_fuerza.getText()), Double.parseDouble(tf_agfisica.getText()),
                        Double.parseDouble(tf_agmental.getText()), Double.parseDouble(tf_vida.getText())   ));
                
                
                //Añadir al arbol
                DefaultTreeModel m = (DefaultTreeModel) jt_personajes.getModel();
                DefaultMutableTreeNode raiz
                        = (DefaultMutableTreeNode) m.getRoot();
                
                
                DefaultMutableTreeNode nodo_personaje;
                nodo_personaje
                        = new DefaultMutableTreeNode(
                                new Personajes(tf_nombre.getText(), tf_poder.getText(),
                        tf_debilidad.getText(), cb_universo.getSelectedItem().toString(),
                          Double.parseDouble(tf_fuerza.getText()), Double.parseDouble(tf_agfisica.getText()),
                        Double.parseDouble(tf_agmental.getText()), Double.parseDouble(tf_vida.getText()))
                                );
                String universo = cb_universo.getSelectedItem().toString();
                
                int centinela = -1;           
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().
                            equals(universo)) {
                        
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(nodo_personaje);
                        centinela = 1;
                    } //fin if
                } //fin for  

                if (centinela == -1) {
                    DefaultMutableTreeNode u
                            = new DefaultMutableTreeNode(universo);
                    
                    u.add(nodo_personaje);
                    raiz.add(u);
                }  // fin if
                m.reload();
                
                //set text
                tf_poder.setText("");
                tf_debilidad.setText("");
                tf_agmental.setText("");
                tf_agfisica.setText("");
                tf_fuerza.setText("");
                tf_vida.setText("");
                tf_nombre.setText("");
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Llenar todos los campos");
            }
    }//GEN-LAST:event_jb_addActionPerformed

    private void jl_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresarMouseClicked
        jl_regresar.setForeground(Color.white);
        jf_agregarpersonajes.dispose();
        regresarmain();
    }//GEN-LAST:event_jl_regresarMouseClicked

    private void jl_regresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresarMouseEntered
        jl_regresar.setForeground(Color.blue);
    }//GEN-LAST:event_jl_regresarMouseEntered

    private void jl_regresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresarMouseExited
        jl_regresar.setForeground(Color.white);
    }//GEN-LAST:event_jl_regresarMouseExited

    private void jb_listarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_listarpActionPerformed
        listarpersonaje();
        jp_listpersonaje.setVisible(false);
        jp_listpersonajes.setVisible(false);
        jp_modpersonaje.setVisible(false);
        jp_delpersonaje.setVisible(false);
    }//GEN-LAST:event_jb_listarpActionPerformed

    private void jt_personajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_personajesMouseClicked
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jt_personajes.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_personajes.setSelectionRow(row);
            Object v1
                    = jt_personajes.getSelectionPath().
                    getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (!nodo_seleccionado.isRoot()) {
                if (nodo_seleccionado.getUserObject() instanceof Personajes) {
                    pm_crud.show(evt.getComponent(),evt.getX(), evt.getY());
                    mi_eliminar.setVisible(true);
                    mi_modificar.setVisible(true);
                }else{
                    pm_crud.show(evt.getComponent(),evt.getX(), evt.getY());
                    mi_eliminar.setVisible(false);
                    mi_modificar.setVisible(false);
                }
                
            }
        }
    }//GEN-LAST:event_jt_personajesMouseClicked

    private void jl_regresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresar1MouseClicked
        jl_regresar1.setForeground(Color.white);
        jf_listarpersonajes.dispose();
        regresarmain();
    }//GEN-LAST:event_jl_regresar1MouseClicked

    private void jl_regresar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresar1MouseEntered
        jl_regresar1.setForeground(Color.blue);
    }//GEN-LAST:event_jl_regresar1MouseEntered

    private void jl_regresar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresar1MouseExited
        jl_regresar1.setForeground(Color.white);
    }//GEN-LAST:event_jl_regresar1MouseExited

    private void mi_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_listarActionPerformed
        
        if (nodo_seleccionado.getUserObject() instanceof Personajes) {
            personaje_seleccionado = (Personajes) nodo_seleccionado.getUserObject();
            jp_listpersonaje.setVisible(true);
            jp_listpersonajes.setVisible(false);
            jp_modpersonaje.setVisible(false);
            jp_delpersonaje.setVisible(false);
            
            jt_personaje.setText(personaje_seleccionado.getNombre());
            //DefaultListModel modelo = (DefaultListModel) jl_infopersonaje.getModel();
            DefaultListModel<String> listModel =new DefaultListModel<>();
            
            String s="\nPoder ->"+personaje_seleccionado.getPoder();
            listModel.addElement(s);
            jl_infopersonaje.setModel(listModel);
            
            s="\nDebilidad ->"+personaje_seleccionado.getDebilidad();
            listModel.addElement(s);
            jl_infopersonaje.setModel(listModel);
            
            s="\nUniverso ->"+personaje_seleccionado.getUniverso();
            listModel.addElement(s);
            jl_infopersonaje.setModel(listModel);
            
            s="\nFuerza ->"+personaje_seleccionado.getFuerza();
            listModel.addElement(s);
            jl_infopersonaje.setModel(listModel);
            
            s="\nAgilidad Fisica ->"+personaje_seleccionado.getAg_fisica();
            listModel.addElement(s);
            jl_infopersonaje.setModel(listModel);
            
            s="\nAgilidad Mental ->"+personaje_seleccionado.getAg_mental();
            listModel.addElement(s);
            jl_infopersonaje.setModel(listModel);
            
            s="\nVida ->"+personaje_seleccionado.getVida();
            listModel.addElement(s);
            jl_infopersonaje.setModel(listModel);

            
        }else{
            jp_listpersonaje.setVisible(false);
            jp_listpersonajes.setVisible(true);
            listarTabla(0);
            jp_modpersonaje.setVisible(false);
            jp_delpersonaje.setVisible(false);
        }
    }//GEN-LAST:event_mi_listarActionPerformed

    private void mi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_eliminarActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            personaje_seleccionado = (Personajes) nodo_seleccionado.getUserObject();
            DefaultTreeModel m
                    = (DefaultTreeModel) jt_personajes.getModel();
            m.removeNodeFromParent(
                    nodo_seleccionado);
            m.reload();
            for (int i = 0; i < personaje.size(); i++) {
                Personajes p = personaje.get(i);
                if (p.getNombre().equals(personaje_seleccionado.getNombre())) {
                    personaje.remove(i);
                }
            }
        }
        
    }//GEN-LAST:event_mi_eliminarActionPerformed

    private void jb_batallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_batallaActionPerformed
        simulacion();
    }//GEN-LAST:event_jb_batallaActionPerformed

    private void jb_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gameActionPerformed
        if (jList1.getSelectedIndex() >= 0&&jList2.getSelectedIndex() >= 0) {
            game();
        }
        jl_personaje.setText(personaje1.getNombre());
        jl_personaje.setForeground(Color.green);
        
    }//GEN-LAST:event_jb_gameActionPerformed

    private void cb_personajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_personajeItemStateChanged
        if (evt.getStateChange()==2) {
            String s = cb_personaje.getSelectedItem().toString();
            DefaultListModel modelo
                    = (DefaultListModel) jList1.getModel();
            modelo.removeAllElements();
            for (int i = 0; i < personaje.size(); i++) {
                String p = personaje.get(i).getUniverso();
                if (p.equals(s)) {
                    modelo.addElement(personaje.get(i).getNombre()
                    );
                    jList1.setModel(modelo);
                }
            }
        }
    }//GEN-LAST:event_cb_personajeItemStateChanged

    private void cb_personaje2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_personaje2ItemStateChanged
        if (evt.getStateChange()==2) {
            String s = cb_personaje2.getSelectedItem().toString();
            DefaultListModel modelo
                    = (DefaultListModel) jList2.getModel();
            modelo.removeAllElements();
            for (int i = 0; i < personaje.size(); i++) {
                String p = personaje.get(i).getUniverso();
                if (p.equals(s)) {
                    modelo.addElement(personaje.get(i).getNombre()
                    );
                    jList2.setModel(modelo);
                }
            }
        }
    }//GEN-LAST:event_cb_personaje2ItemStateChanged

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (jList1.getSelectedIndex() >= 0) {
            String p = jList1.getSelectedValue();
            for (Personajes t : personaje) {
                if (p.equals(t.getNombre())) {
                    personaje1 = t;
                }
            }
//            personaje1 = ((Personajes) modeloLISTA.get(
//                    jList1.getSelectedIndex()) );
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if (jList2.getSelectedIndex() >= 0) {
            String p = jList2.getSelectedValue();
            for (Personajes t : personaje) {
                if (p.equals(t.getNombre())) {
                    personaje2 = t;
                }
            }
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void jl_regresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresar2MouseClicked
        jl_regresar2.setForeground(Color.white);
        jf_seleccion.dispose();
        regresarmain();
    }//GEN-LAST:event_jl_regresar2MouseClicked

    private void jl_regresar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresar2MouseEntered
        jl_regresar2.setForeground(Color.blue);
    }//GEN-LAST:event_jl_regresar2MouseEntered

    private void jl_regresar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresar2MouseExited
        jl_regresar2.setForeground(Color.white);
    }//GEN-LAST:event_jl_regresar2MouseExited

    private void jl_regresar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresar3MouseClicked
        jl_regresar3.setForeground(Color.white);
        regresarsim();
    }//GEN-LAST:event_jl_regresar3MouseClicked

    private void jl_regresar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresar3MouseEntered
        jl_regresar3.setForeground(Color.blue);
    }//GEN-LAST:event_jl_regresar3MouseEntered

    private void jl_regresar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regresar3MouseExited
        jl_regresar3.setForeground(Color.white);
    }//GEN-LAST:event_jl_regresar3MouseExited

    private void jb_resistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_resistenciaActionPerformed
        String s1 =jl_personaje.getText();
        String s2 = personaje1.getNombre();
        String s3 = personaje2.getNombre();
        if (personaje1.getVida()>0&&personaje2.getVida()>0) {
            if (s1.equals(s2)) {
                //personaje1
                double vida = personaje1.getVida()*0.15;
                personaje1.setVida(personaje1.getVida()+vida);

                double vida2 = personaje1.getFuerza()*0.15;
                personaje2.setVida(personaje2.getVida()-vida2);

                area+= "\n Ataco "+personaje1.getNombre()+"\n Vida: "+personaje1.getVida()
                        +"\n Vida de "+personaje2.getNombre()+": "+personaje2.getVida();
                ta_juego.setText(area);
                //Colorear
                ataque1=1;
                if (ataque2==0) {
                    jl_personaje.setText(personaje2.getNombre());
                    jl_personaje.setForeground(Color.red);
                }else{
                    ataque2=0;
                }
                if (personaje2.getVida()<=0) {
                    area+="\n\n"+personaje1.getNombre()+" ha ganado";
                }


            }
            if (s1.equals(s3)) {
                //personaje2

                double vida = personaje2.getVida()*0.15;
                personaje2.setVida(personaje2.getVida()+vida);

                double vida2 = personaje2.getFuerza()*0.15;
                personaje1.setVida(personaje1.getVida()-vida2);

                area+= "\n Ataco "+personaje2.getNombre()+"\n Vida: "+personaje2.getVida()
                        +"\nVida de "+personaje1.getNombre()+": "+personaje1.getVida();
                ta_juego.setText(area);

                //Colorear
                ataque2=1;
                if (ataque1==0) {
                    jl_personaje.setText(personaje1.getNombre());
                    jl_personaje.setForeground(Color.green);
                }else{
                    ataque1=0;
                }
                if (personaje1.getVida()<=0) {
                    area+="\n\n"+personaje2.getNombre()+" ha ganado";
                }


            }
        }
            
        
    }//GEN-LAST:event_jb_resistenciaActionPerformed

    private void jb_mentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mentalActionPerformed
        String s1 =jl_personaje.getText();
        String s2 = personaje1.getNombre();
        String s3 = personaje2.getNombre();
        if (personaje1.getVida()>0&&personaje2.getVida()>0) {
            if (s1.equals(s2)) {
                double vida = personaje1.getAg_mental()*0.3;
                personaje2.setVida(personaje2.getVida()-vida);

                area+= "\n Ataco "+personaje1.getNombre()+"a "+personaje2.getNombre()
                        +"\n Cuya vida quedo en:  "+personaje2.getVida()
                        +"\n Ataque Mental: "+vida;
                ta_juego.setText(area);

                //Colorear
                if (ataque2==0) {
                    jl_personaje.setText(personaje2.getNombre());
                    jl_personaje.setForeground(Color.red);
                }else{
                ataque2=0;}
                if (personaje2.getVida()<=0) {
                    area+="\n\n"+personaje1.getNombre()+" ha ganado";
                }
            }
            if (s1.equals(s3)) {
                double vida = personaje2.getAg_mental()*0.15;
                personaje1.setVida(personaje1.getVida()-vida);

                area+= "\n Ataco "+personaje2.getNombre()+"a "+personaje1.getNombre()
                        +"\n Cuya vida quedo en:  "+personaje1.getVida()
                        +"\n Ataque Mental: "+vida;
                ta_juego.setText(area);

                //Colorear
                if (ataque1==0) {
                    jl_personaje.setText(personaje1.getNombre());
                    jl_personaje.setForeground(Color.green);
                }else{
                ataque1=0;}
                if (personaje1.getVida()<=0) {
                    area+="\n\n"+personaje2.getNombre()+" ha ganado";
                }

            }
        }
            
    }//GEN-LAST:event_jb_mentalActionPerformed

    private void jb_fisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_fisicoActionPerformed
        String s1 =jl_personaje.getText();
        String s2 = personaje1.getNombre();
        String s3 = personaje2.getNombre();
        if (personaje1.getVida()>0&&personaje2.getVida()>0) {
            if (s1.equals(s2)) {
                double vida = personaje1.getAg_fisica()/2;
                personaje2.setVida(personaje2.getVida()-vida);

                area+= "\n Ataco "+personaje1.getNombre()+"a "+personaje2.getNombre()
                        +"\n Cuya vida quedo en:  "+personaje2.getVida()
                        +"\n Ataque fisico: "+vida;
                ta_juego.setText(area);

                if (ataque2==0) {
                    jl_personaje.setText(personaje2.getNombre());
                    jl_personaje.setForeground(Color.red);
                }else{
                    ataque2=0;
                }
                if (personaje2.getVida()<=0) {
                    area+="\n\n"+personaje1.getNombre()+" ha ganado";
                }
            }
            if (s1.equals(s3)) {
                double vida = personaje2.getAg_fisica()/2;
                personaje1.setVida(personaje1.getVida()-vida);

                area+= "\n Ataco "+personaje2.getNombre()+"a "+personaje1.getNombre()
                        +"\n Cuya vida quedo en:  "+personaje1.getVida()
                        +"\n Ataque fisico: "+vida;
                ta_juego.setText(area);

                if (ataque1==0) {
                    jl_personaje.setText(personaje1.getNombre());
                    jl_personaje.setForeground(Color.green);
                }else{
                    ataque1=0;
                }
                if (personaje1.getVida()<=0) {
                    area+="\n\n"+personaje2.getNombre()+" ha ganado";
                }
            }
        }
            
    }//GEN-LAST:event_jb_fisicoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void agregarpersonaje (){
        this.dispose();
        
        jf_agregarpersonajes.pack();//para que la ventana se abra correctamente
        jf_agregarpersonajes.setLocationRelativeTo(this);
        jf_agregarpersonajes.setExtendedState(MAXIMIZED_BOTH);
        //jf_agregarpersonajes.setModal(true);//hacer prioridad la ventana
        jf_agregarpersonajes.setVisible(true);
    }
    private void simulacion (){
        this.dispose();
        
        jf_seleccion.pack();//para que la ventana se abra correctamente
        jf_seleccion.setLocationRelativeTo(this);
        jf_seleccion.setExtendedState(MAXIMIZED_BOTH);
        //jf_agregarpersonajes.setModal(true);//hacer prioridad la ventana
        jf_seleccion.setVisible(true);
    }
    private void game(){
        this.dispose();
        area="";
        jf_game.pack();//para que la ventana se abra correctamente
        jf_game.setLocationRelativeTo(this);
        jf_game.setExtendedState(MAXIMIZED_BOTH);
        //jf_agregarpersonajes.setModal(true);//hacer prioridad la ventana
        jf_game.setVisible(true);
    }
    
    private void listarpersonaje (){
        this.dispose();
        
        jf_listarpersonajes.pack();
        jf_listarpersonajes.setLocationRelativeTo(this);
        //jf_listarpersonajes.setModal(true);
        //jf_listarpersonajes.setExtendedState(MAXIMIZED_BOTH);
        jf_listarpersonajes.setVisible(true);
    }
    
    private void regresarsim(){
        jf_game.dispose();
        jf_seleccion.pack();
        jf_seleccion.setLocationRelativeTo(this);
        jf_seleccion.setExtendedState(MAXIMIZED_BOTH);
        jf_seleccion.setVisible(true);
    }
    
    private void regresarmain(){
        
        this.pack();
        this.setLocationRelativeTo(this);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(true);
    }
    
//    private void infoarbol(){
//        
//    }
    
//    private String listap(Personajes p){
//        String s;
//        s = "\nPoder ->"+p.getPoder()
//                +"\nDebilidad ->"+p.getDebilidad()
//                +"\nUniverso ->"+p.getUniverso()
//                +"\nFuerza ->"+p.getFuerza()
//                +"\nAgilidad Fisica ->"+p.getAg_fisica()
//                +"\nAgilidad Mental ->"+p.getAg_mental()
//                +"\nVida ->"+p.getVida();
//        
//        return s;
//    }
    
    private void listarTabla(int x) {
        try {
            if(x==0){
                //limpiar tabla
                tb_personajes.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre", "Poder", "Debilidad", "Universo","Fuerza","Ag.Fisica","Ag.Mental","Vida"
                        }
                ));
                for (Personajes t : personaje) {
                    String nodo = nodo_seleccionado.getUserObject().toString();
                    if (nodo.equals(t.getUniverso())) {
                        Object[] row = {t.getNombre(),t.getPoder(),t.getDebilidad(),t.getUniverso(),t.getFuerza(),
                        t.getAg_fisica(),t.getAg_mental(),t.getVida()  };

                        DefaultTableModel modelo = (DefaultTableModel) tb_personajes.getModel();
                        modelo.addRow(row);
                        tb_personajes.setModel(modelo);
                    }

                }
            }
            if (x==1) {
                tb_personajes.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre", "Poder", "Debilidad", "Universo","Fuerza","Ag.Fisica","Ag.Mental","Vida"
                        }
                ));
                for (Personajes t : personaje) {
                    String nodo = nodo_seleccionado.getUserObject().toString();
                    if (nodo.equals(t.getUniverso())) {
                        Object[] row = {t.getNombre(),t.getPoder(),t.getDebilidad(),t.getUniverso(),t.getFuerza(),
                        t.getAg_fisica(),t.getAg_mental(),t.getVida()  };

                        DefaultTableModel modelo = (DefaultTableModel) tb_personajes.getModel();
                        modelo.addRow(row);
                        tb_personajes.setModel(modelo);
                    }

                }
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    ArrayList<Personajes> personaje = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Personajes personaje_seleccionado;
    Personajes personaje1=null;
    Personajes personaje2=null;
    int ataque1=0;//0 = no, 1 = si
    int ataque2=0;//0 = no, 1 = si
    String area="";
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_personaje;
    private javax.swing.JComboBox<String> cb_personaje2;
    private javax.swing.JComboBox cb_universo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jb_add;
    private javax.swing.JButton jb_agregarp;
    private javax.swing.JButton jb_batalla;
    private javax.swing.JToggleButton jb_fisico;
    private javax.swing.JButton jb_game;
    private javax.swing.JButton jb_listarp;
    private javax.swing.JToggleButton jb_mental;
    private javax.swing.JToggleButton jb_resistencia;
    private javax.swing.JFrame jf_agregarpersonajes;
    private javax.swing.JFrame jf_game;
    private javax.swing.JFrame jf_listarpersonajes;
    private javax.swing.JFrame jf_seleccion;
    private javax.swing.JList<String> jl_infopersonaje;
    private javax.swing.JLabel jl_personaje;
    private javax.swing.JLabel jl_regresar;
    private javax.swing.JLabel jl_regresar1;
    private javax.swing.JLabel jl_regresar2;
    private javax.swing.JLabel jl_regresar3;
    private javax.swing.JPanel jp_delpersonaje;
    private javax.swing.JPanel jp_listpersonaje;
    private javax.swing.JPanel jp_listpersonajes;
    private javax.swing.JPanel jp_modpersonaje;
    private javax.swing.JTextField jt_personaje;
    private javax.swing.JTree jt_personajes;
    private javax.swing.JMenuItem mi_eliminar;
    private javax.swing.JMenuItem mi_listar;
    private javax.swing.JMenuItem mi_modificar;
    private javax.swing.JPopupMenu pm_crud;
    private javax.swing.JTextArea ta_juego;
    private javax.swing.JTable tb_personajes;
    private javax.swing.JTextField tf_agfisica;
    private javax.swing.JTextField tf_agmental;
    private javax.swing.JTextField tf_debilidad;
    private javax.swing.JTextField tf_fuerza;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_poder;
    private javax.swing.JTextField tf_vida;
    // End of variables declaration//GEN-END:variables
}
